src/Entity/Package.php
<?php

namespace App\Entity;

use DateInterval;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PackageRepository")
 */
class Package
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $aport;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $arch;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $component;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PackageDependency", mappedBy="package", orphanRemoval=true)
     */
    private $packageDependencies;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Queue", mappedBy="package", orphanRemoval=true)
     */
    private $versions;

    /**
     * @ORM\Column(type="bigint", nullable=true)
     */
    private $timeSpent;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $timesBuilt;


    public function __construct()
    {
        $this->packageDependencies = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getAport()
    {
        return $this->aport;
    }

    /**
     * @param mixed $aport
     */
    public function setAport($aport)
    {
        $this->aport = $aport;
    }

    /**
     * @return mixed
     */
    public function getArch()
    {
        return $this->arch;
    }

    /**
     * @param mixed $arch
     */
    public function setArch($arch)
    {
        $this->arch = $arch;
    }


    /**
     * @return Collection|PackageDependency[]
     */
    public function getQueueDependencies()
    {
        return $this->packageDependencies;
    }

    public function addQueueDependency(PackageDependency $queueDependency): self
    {
        if (!$this->packageDependencies->contains($queueDependency)) {
            $this->packageDependencies[] = $queueDependency;
            $queueDependency->setPackage($this);
        }

        return $this;
    }

    public function removeQueueDependency(PackageDependency $queueDependency): self
    {
        if ($this->packageDependencies->contains($queueDependency)) {
            $this->packageDependencies->removeElement($queueDependency);
            // set the owning side to null (unless already changed)
            if ($queueDependency->getPackage() === $this) {
                $queueDependency->setPackage(null);
            }
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getComponent()
    {
        return $this->component;
    }

    /**
     * @param string $component
     */
    public function setComponent($component)
    {
        $this->component = $component;
    }

    /**
     * @return Queue[]
     */
    public function getVersions()
    {
        return $this->versions;
    }

    /**
     * @param mixed $versions
     */
    public function setVersions($versions)
    {
        $this->versions = $versions;
    }

    /**
     * @return mixed
     */
    public function getTimeSpent()
    {
        return $this->timeSpent;
    }

    /**
     * @param mixed $timeSpent
     */
    public function setTimeSpent($timeSpent)
    {
        $this->timeSpent = $timeSpent;
    }

    /**
     * @return mixed
     */
    public function getTimesBuilt()
    {
        return $this->timesBuilt;
    }

    /**
     * @param mixed $timesBuilt
     */
    public function setTimesBuilt($timesBuilt)
    {
        $this->timesBuilt = $timesBuilt;
    }

    public function getAverageBuildTime()
    {
        if ($this->timesBuilt > 0) {
            $seconds = $this->timeSpent / $this->timesBuilt;
            $result = DateInterval::createFromDateString($this->timeSpent . ' seconds');
            $result->h = floor($seconds / 60 / 60);
            $seconds -= $result->h * 3600;
            $result->i = floor($seconds / 60);
            $seconds -= $result->i * 60;
            $result->s = $seconds;
            return $result;
        }
        return null;
    }
}

src/Controller/StatusController.php
<?php

namespace App\Controller;

use App\Entity\Commit;
use App\Entity\Package;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StatusController extends Controller
{
    /**
     * @Route("/", name="status")
     * @Route("/queue", name="queue")
     */
    public function queue()
    {
        $queue = $this->getDoctrine()->getRepository('App:Queue');
        $queued = $queue->findBy(['status' => ['WAITING', 'BUILDING']], ['id' => 'DESC']);
        $done = $queue->findBy(['status' => ['DONE', 'FAILED', 'SUPERSEDED']], ['id' => 'DESC'], 50);
        return $this->render('status/queue.html.twig', [
            'queued' => $queued,
            'done' => $done,
            'srht_namespace' => $this->getParameter('srht_namespace'),
        ]);
    }

    /**
     * @Route("/packages", name="packages")
     */
    public function packages()
    {
        $packages = $this->getDoctrine()->getRepository('App:Package')->findBy([], ['aport' => 'ASC']);
        return $this->render('status/packages.html.twig', [
            'packages' => $packages,
        ]);
    }

    /**
     * @Route("/commits", name="commits")
     */
    public function commits()
    {
        $queue = $this->getDoctrine()->getRepository('App:Commit');

        $raw = $queue->findBy([], ['id' => 'DESC'], 75);
        $queued = [];
        $done = [];

        foreach ($raw as $r) {
            if (in_array($r->getStatus(), ['DONE', 'FAILED', 'SUPERSEDED'])) {
                $done[] = $r;
            } else {
                $queued[] = $r;
            }
        }
        return $this->render('status/commits.html.twig', [
            'queued' => $queued,
            'done' => $done
        ]);
    }

    /**
     * @Route("/commits/{ref}", name="commit_details")
     */
    public function commitDetails($ref)
    {
        $commits = $this->getDoctrine()->getRepository('App:Commit');
        $commit = $commits->findOneBy(['ref' => $ref]);
        /** @var Commit $commit */
        $tasks = $commit->getTasks();

        $cacheKey = $commit->getRef();
        $hash = '';
        foreach ($tasks as $task) {
            $hash .= $task->getStatus();
        }
        $cacheKey .= '-' . md5($hash);

        $outFile = $this->getParameter('kernel.project_dir') . '/public/commit/' . $cacheKey . '.png';

        if (!file_exists($outFile)) {

            $graph = 'digraph g {' . PHP_EOL . '    rankdir=LR;' . PHP_EOL;
            foreach ($tasks as $task) {
                $package = $task->getPackage();
                $label = $package->getAport() . ' ' . $task->getPkgver() . '-r' . $task->getPkgrel();
                switch ($task->getStatus()) {
                    case "WAITING":
                        $color = 'azure1';
                        break;
                    case "BUILDING":
                        $color = 'azure3';
                        break;
                    case "FAILED":
                        $color = 'tomato';
                        break;
                    case "DONE":
                        $color = 'darkolivegreen1';
                        break;
                    case "SUPERSEDED":
                        $color = 'blanchedalmond'; //because why not
                        break;
                }
                $graph .= '    "' . $package->getAport() . '"[label="' . $label . '" fillcolor=' . $color . ' style=filled]' . PHP_EOL;
            }
            $graph .= PHP_EOL . PHP_EOL;
            foreach ($tasks as $task) {
                $package = $task->getPackage();
                foreach ($package->getQueueDependencies() as $dependency) {
                    $graph .= '    "' . $dependency->getRequirement()->getAport() . '" -> "' . $package->getAport() . '"' . PHP_EOL;
                }
            }
            $graph .= ' }';

            $inFile = $this->getParameter('kernel.project_dir') . '/public/commit/' . $cacheKey . '.dot';
            file_put_contents($inFile, $graph);
            exec('dot "' . $inFile . '" -o "' . $outFile . '" -Tpng');
        }


        return $this->render('status/commit.html.twig', ['ref' => $ref, 'key' => $cacheKey]);
    }

    /**
     * @Route("/log", name="log")
     */
    public function log()
    {
        $log = $this->getDoctrine()->getRepository('App:Log')->findBy([], ['datetime' => 'DESC']);
        return $this->render('status/log.html.twig', [
            'log' => $log,
        ]);
    }
}

templates/status/commit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commit detail{% endblock %}

{% block body %}
    <a href="{{ path('packages') }}">Packages</a> | <a href="{{ path('commits') }}">Commits</a>

    <h2>Commit detail</h2>
    <img src="/commit/{{ key }}.png" class="img-responsive">
{% endblock %}

templates/status/commits.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commits{% endblock %}

{% block body %}
    <a href="{{ path('queue') }}">Queue</a> | <a href="{{ path('packages') }}">Packages</a> | Commits

    <h2>Pending commits</h2>
    <table class="collapse ba b--black-10 table">
        <tr class="striped--near-white">
            <th>#</th>
            <th>branch</th>
            <th>commit</th>
            <th>status</th>
            <th>message</th>
        </tr>
        {% for commit in queued %}
            <tr class="striped--near-white">
                <td>
                    <a href="{{ path('commit_details', {'ref': commit.ref}) }}">
                        {{ commit.id }}
                    </a>
                </td>
                <td>{{ commit.branch }}</td>
                <td>
                    <a href="https://gitlab.com/postmarketOS/pmaports/commit/{{ commit.ref }}"
                       style="font-family: monospace;">
                        {{ commit.ref | slice(0, 8) }}
                    </a>
                </td>
                <td>{{ commit.status }}</td>
                <td>{{ commit.message }}</td>
            </tr>
        {% endfor %}
    </table>

    <h2>Completed commits</h2>
    <table class="collapse ba b--black-10 table">
        <tr class="striped--near-white">
            <th>#</th>
            <th>branch</th>
            <th>commit</th>
            <th>status</th>
            <th>message</th>
        </tr>
        {% for commit in done %}
            <tr class="striped--near-white">
                <td>{{ commit.id }}</td>
                <td>{{ commit.branch }}</td>
                <td>
                    <a href="https://gitlab.com/postmarketOS/pmaports/commit/{{ commit.ref }}">
                        {{ commit.ref | slice(0, 8) }}
                    </a>
                </td>
                <td>{{ commit.status }}</td>
                <td>{{ commit.message }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/status/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Queue{% endblock %}

{% block body %}
    <h2>Pending builds</h2>
    <table class="collapse ba b--black-10 table">
        <tr class="striped--near-white">
            <th>#</th>
            <th>aport</th>
            <th>pkgver</th>
            <th>pkgrel</th>
            <th>branch</th>
            <th>arch</th>
            <th>commit</th>
            <th>sr.ht id</th>
            <th>status</th>
        </tr>
        {% for job in queued %}
            <tr class="striped--near-white">
                <td>{{ job.id }}</td>
                <td>{{ job.aport }}</td>
                <td>{{ job.pkgver }}</td>
                <td>{{ job.pkgrel }}</td>
                <td>{{ job.branch }}</td>
                <td>{{ job.arch }}</td>
                <td>
                    <a href="https://gitlab.com/postmarketOS/pmaports/commit/{{ job.commit.ref }}">
                        {{ job.commit.ref | slice(0, 8) }}
                    </a>
                </td>
                <td>
                    <a href="https://builds.sr.ht/~pmos/job/{{ job.srhtId }}">
                        {{ job.srhtId }}
                    </a>
                </td>
                <td>{{ job.status }}</td>
            </tr>
        {% endfor %}
    </table>

    <h2>Completed builds</h2>
    <table class="collapse ba b--black-10 table">
        <tr class="striped--near-white">
            <th>#</th>
            <th>aport</th>
            <th>pkgver</th>
            <th>pkgrel</th>
            <th>branch</th>
            <th>arch</th>
            <th>commit</th>
            <th>sr.ht id</th>
            <th>status</th>
        </tr>
        {% for job in done %}
            <tr class="striped--near-white">
                <td>{{ job.id }}</td>
                <td>
                    <a href="http://postmarketos.brixit.nl/{{ job.arch }}/{{ job.aport }}-{{ job.pkgver }}-r{{ job.pkgrel }}.apk">
                        {{ job.aport }}
                    </a>
                </td>
                <td>{{ job.pkgver }}</td>
                <td>{{ job.pkgrel }}</td>
                <td>{{ job.branch }}</td>
                <td>{{ job.arch }}</td>
                <td>
                    <a href="https://gitlab.com/postmarketOS/pmaports/commit/{{ job.commit }}">
                        {{ job.commit | slice(0, 8) }}
                    </a>
                </td>
                <td>
                    <a href="https://builds.sr.ht/~pmos/job/{{ job.srhtId }}">
                        {{ job.srhtId }}
                    </a>
                </td>
                <td>{{ job.status }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/status/log.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log{% endblock %}

{% block body %}
    <h2>Log messages</h2>
    <table class="collapse ba b--black-10 table">
        <tr class="striped--near-white">
            <th>time</th>
            <th>action</th>
            <th>detail</th>
        </tr>
        {% for message in log %}
            <tr class="striped--near-white">
                <td>{{ message.datetime | date }}</td>
                <td>{{ message.action }}</td>
                <td>
                    {% if message.details is not none %}
                        <pre>
{{ message.details }}
</pre>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/status/packages.html.twig
{% extends 'base.html.twig' %}

{% block title %}Packages{% endblock %}

{% block body %}
    <a href="{{ path('queue') }}">Queue</a> | Packages | <a href="{{ path('commits') }}">Commits</a>

    <h2>Packages</h2>
    <table class="collapse ba b--black-10 table">
        <tr class="striped--near-white">
            <th>#</th>
            <th>name</th>
            <th>arch</th>
            <th>Average build time</th>
        </tr>
        {% for package in packages %}
            <tr class="striped--near-white">
                <td>{{ package.id }}</td>
                <td>{{ package.aport }}</td>
                <td>{{ package.arch }}</td>
                <td>
                    {% if package.averageBuildTime is not null %}
                        {{ package.averageBuildTime | date('%hh %Im %Ss')  }}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/status/queue.html.twig
{% extends 'base.html.twig' %}

{% block title %}Packages{% endblock %}

{% block body %}
    Queue | <a href="{{ path('packages') }}">Packages</a> | <a href="{{ path('commits') }}">Commits</a>

    <h2>Pending builds</h2>
    <table class="collapse ba b--black-10 table">
        <tr class="striped--near-white">
            <th>#</th>
            <th>aport</th>
            <th>pkgver</th>
            <th>branch</th>
            <th>arch</th>
            <th>commit</th>
            <th>sr.ht id</th>
            <th>status</th>
        </tr>
        {% for job in queued %}
            <tr class="striped--near-white">
                <td>{{ job.id }}</td>
                <td>{{ job.package.aport }}</td>
                <td>{{ job.pkgver }}-{{ job.pkgrel }}</td>
                <td>{{ job.commit.branch }}</td>
                <td>{{ job.package.arch }}</td>
                <td>
                    <a href="https://gitlab.com/postmarketOS/pmaports/commit/{{ job.commit.ref }}"
                       style="font-family: monospace;">
                        {{ job.commit.ref | slice(0, 8) }}
                    </a>
                </td>
                <td>
                    {% if job.srhtId is not null %}
                        <a href="https://builds.sr.ht/{{srht_namespace}}/job/{{ job.srhtId }}">
                            {{ job.srhtId }}
                        </a>
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>{{ job.status }}</td>
            </tr>
        {% endfor %}
    </table>

    <h2>Completed builds</h2>
    <table class="collapse ba b--black-10 table">
        <tr class="striped--near-white">
            <th>#</th>
            <th>aport</th>
            <th>pkgver</th>
            <th>branch</th>
            <th>arch</th>
            <th>time</th>
            <th>commit</th>
            <th>sr.ht id</th>
            <th>status</th>
        </tr>
        {% for job in done %}
            <tr class="striped--near-white">
                <td>{{ job.id }}</td>
                <td>{{ job.package.aport }}</td>
                <td>{{ job.pkgver }}-{{ job.pkgrel }}</td>
                <td>{{ job.commit.branch }}</td>
                <td>{{ job.package.arch }}</td>
                <td>{{ job.timeSpent | date('%hh %Im %Ss') }}</td>
                <td>
                    <a href="https://gitlab.com/postmarketOS/pmaports/commit/{{ job.commit.ref }}"
                       style="font-family: monospace;">
                        {{ job.commit.ref | slice(0, 8) }}
                    </a>
                </td>
                <td>
                    <a href="https://builds.sr.ht/~pmos/job/{{ job.srhtId }}">
                        {{ job.srhtId }}
                    </a>
                </td>
                <td>
                    {% if job.status == 'DONE' %}
                        <a href="/repository/{{ job.commit.branch }}/{{ job.package.component }}/{{ job.package.arch }}/{{ job.package.aport }}-{{ job.pkgver }}-r{{ job.pkgrel }}.apk">
                            DONE
                        </a>
                    {% else %}
                        {{ job.status }}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}